### ISSUE TITLE
Fail to get bizday

### ISSUE THREAD

**Issue by bergpb** [wilsonfreitas/python-bizdays#24]
My code:

from bizdays import Calendar
holidays = ['2017-01-01','2017-04-2017','2017-05-2017','2017-09-07','2017-10-12','2017-11-11','2017-11-15','2017-12-25']
cal = Calendar(holidays=holidays, weekdays=['Sunday', 'Saturday'])
cal.isbizday('2017-11-01')

The output:
Traceback (most recent call last):
  File "dias_uteis.py", line 10, in <module>
    cal = Calendar(holidays=holidays, weekdays=['Sunday', 'Saturday'])
  File "/usr/local/lib/python2.7/dist-packages/bizdays.py", line 285, in __init__
    self._holidays = [Date(d) for d in holidays]
  File "/usr/local/lib/python2.7/dist-packages/bizdays.py", line 245, in __init__
    d = datetime.strptime(d, format).date()
  File "/usr/lib/python2.7/_strptime.py", line 328, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: 17
*Test on cloud9 ide.

**Comment by bonix-git** [comment]
Hi bergpb,

Your code has two errors: 2017-04-2017  and 2017-05-2017

Try something like this:

holidays = ['2017-01-01','2017-04-17','2017-05-17','2017-09-07','2017-10-12','2017-11-11','2017-11-15','2017-12-25']

What do you think?

**Comment by bergpb** [comment]
awesome works like a charm.
thanks for your help.
