### ISSUE TITLE
Upgrade to numpy 2.x

### ISSUE THREAD

**Issue by 0xg0nz0** [wilsonfreitas/python-bizdays#51]
I noticed when I installed bizdays it triggered a numpy downgrade:

```
 - numpy==2.0.0
 + numpy==1.26.4
```

The current pyproject.toml specifies numpy 1.x. It might be better to remove this entirely and then just pull in the numpy version corresponding to pandas 2.x:

```
numpy = ">=1.26.0"
```

**Comment by wilsonfreitas** [comment]
Done. Thanks!
